spring:
  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: http://localhost:8081
          predicates:
            - Path=/doctor/**
        - id: appointment-service
          uri: http://localhost:8082
          predicates:
            - Path=/appointment/**
            - Path=/availability/**
server:
  port: 8085